plugins {
    id 'java'
}

repositories {
    mavenLocal()
    mavenCentral()

    maven {
        name = "GitHubPackages"
        url = uri("https://maven.pkg.github.com/TP1-2-INGSIS/CNC")
        credentials {
            username = project.findProperty("gpr.user") ?: System.getenv("GITHUB_ACTOR")
            password = project.findProperty("gpr.token") ?: System.getenv("GITHUB_TOKEN")
        }
    }
}

java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(21)
    }
}

test {
    minHeapSize = "5m" // initial heap size
    maxHeapSize = "7m" // maximum heap size
}

dependencies {
    testImplementation 'junit:junit:4.13.1'
    implementation("com.github.TP1-2-INGSIS:app:1.0.0")
    implementation("com.github.TP1-2-INGSIS:interpreter:1.0.0")
    implementation("com.github.TP1-2-INGSIS:lexer:1.0.0")
    implementation("com.github.TP1-2-INGSIS:parser:1.0.0")
    implementation("com.github.TP1-2-INGSIS:linter:1.0.0")
    implementation("com.github.TP1-2-INGSIS:semantic:1.0.0")
    implementation("com.github.TP1-2-INGSIS:common:1.0.0")
    implementation("com.github.TP1-2-INGSIS:ast:1.0.0")
    implementation("com.github.TP1-2-INGSIS:token:1.0.0")
}

test {
    environment "BEST_FOOTBALL_CLUB", "San Lorenzo"
    useJUnit()
}
