plugins {
    id 'java'
}

repositories {
    mavenLocal()
    mavenCentral()

    maven {
        name = "GitHubPackages"
        url = uri("https://maven.pkg.github.com/TP1-2-INGSIS/CNC")
        credentials {
            username = project.findProperty("gpr.user") ?: System.getenv("GITHUB_ACTOR")
            password = project.findProperty("gpr.token") ?: System.getenv("GITHUB_TOKEN")
        }
    }
}

java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(21)
    }
}

test {
    minHeapSize = "5m" // initial heap size
    maxHeapSize = "7m" // maximum heap size
}

dependencies {
    def psVersion = project.findProperty("printscriptVersion") ?: System.getenv("PRINTSCRIPT_VERSION") ?: "1.2.0"

    testImplementation 'junit:junit:4.13.1'
    implementation("com.github.TP1-2-INGSIS:printscript:${psVersion}")
}

test {
    environment "BEST_FOOTBALL_CLUB", "San Lorenzo"
    useJUnit()
}
